import flet as ft

COLOR_PRIMARY = "#1E3A8A"
COLOR_PRIMARY_HOVER = "#172554"
COLOR_SECONDARY = "#3B82F6"
COLOR_SECONDARY_HOVER = "#DBEAFE"
COLOR_BACKGROUND = "#F8FAFC"
COLOR_SURFACE = "#FFFFFF"
COLOR_SURFACE_VARIANT = "#F1F5F9"
COLOR_ERROR = "#DC2626"
COLOR_SUCCESS = "#10B981"
COLOR_WARNING = "#F59E0B"
COLOR_TEXT_MAIN = "#0F172A"
COLOR_TEXT_SUB = "#64748B"
COLOR_OUTLINE = "#CBD5E1"
COLOR_OUTLINE_LIGHT = "#E2E8F0"
COLOR_TONAL_BG = "#EFF6FF"
COLOR_TONAL_TEXT = "#1E40AF"

def get_theme():
    return ft.Theme(
        color_scheme=ft.ColorScheme(
            primary=COLOR_PRIMARY,
            surface=COLOR_SURFACE,
            error=COLOR_ERROR,
        )
    )
